### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by jolt2017** [fh2019ustc/DocTr#10]
Great work. So do u have the schedule to realease the traing code？

**Comment by fh2019ustc** [comment]
Thanks for your attention to our work! We will release the training code after the acceptance of DocScanner.

**Comment by mini102** [comment]
I'm a student who interesting your work. So when you'll release the training code?

**Comment by fh2019ustc** [comment]
@mini102 Hi, we will release the training code after the acceptance of [DocScanner](https://arxiv.org/pdf/2110.14968v2.pdf).
