### ISSUE TITLE
Some questions about convex upsample in GeoTr

### ISSUE THREAD

**Issue by KingRicardo** [fh2019ustc/DocTr#20]
I'm a little confused about the use of coords0, coords1, and mask.
Why not just simply used upsample or ConvTranspose
https://github.com/fh2019ustc/DocTr/blob/729fcb8ee23e413a45645de60145cdb115ea1575/GeoTr.py#L226-L233

**Comment by KingRicardo** [comment]
While training GeoTr, which mask do you use to remove the background, the gt mask or the predicted mask by segmentation module?

**Comment by fh2019ustc** [comment]
Yeah, you can use nn.Upsample as an alternative.
In our experiment, the performance of this setting is similar.

**Comment by KingRicardo** [comment]
Thanks a lot for your response!
