### ISSUE TITLE
能否可以提供doc3D数据集

### ISSUE THREAD

**Issue by gocse** [fh2019ustc/DocTr#31]
你好，我这边训练模型苦于没有数据集，也看了[doc3D-dataset](https://github.com/cvlab-stonybrook/doc3D-dataset)也提交了表单，目前没有任何回复，看到issue也有人反馈填写了好几周没回复的。如果可以提供数据集，可以发到我邮箱chenxkj@gmail.com，不会对外提供，仅供自己学习使用，万分感谢。

**Comment by fh2019ustc** [comment]
关于Doc3D数据集，你可以邮件联系我~
