### ISSUE TITLE
About the Doc3d dataset.

### ISSUE THREAD

**Issue by Morton9** [fh2019ustc/DocTr#4]
Who has the method to get the Doc3d dataset? I has not received a reply after the application.

**Comment by fh2019ustc** [comment]
I think you can contact the author of DewarpNet by email.

**Comment by chenyangMl** [comment]
> I think you can contact the author of DewarpNet by email.

Hi, could you share Doc3d dataset with baidu cloud. Cause i cannot cantact with author of DewarpNet. Thanks
