### ISSUE TITLE
what does" bm = (2 * (bm / 286.8) - 1) * 0.99" in inference.py mean?

### ISSUE THREAD

**Issue by quynhanh12345** [fh2019ustc/DocTr#6]

**Comment by fh2019ustc** [comment]
Hi, we use the code "bm = (2 * (bm / 286.8) - 1) * 0.99"  rather than "bm = (2 * (bm / 287) - 1)". The goal is to compensate the coordinate bias from the dataset, which would cause the shifting of the rectified image.

**Comment by lsabrinax** [comment]
did the code "bm = (2 * (bm / 286.8) - 1) * 0.99" use on the pred bm when calculate the BM L1 loss

**Comment by fh2019ustc** [comment]
@lsabrinax It is not used to calculate the flow loss.

**Comment by lsabrinax** [comment]
> @lsabrinax It is not used to calculate the flow loss.

thank you for your reply,  does it mean the GeoTr model directly regress the absolute value in flow  between 0-287

**Comment by fh2019ustc** [comment]
@lsabrinax Yeah~
