### ISSUE TITLE
About training 

### ISSUE THREAD

**Issue by CVUsers** [fh2019ustc/DocTr#7]
Hello, 1: when are you going to open source training? 2: How fast is your plan? 3: What is used in the document detection of your scheme and how is the effect

**Comment by fh2019ustc** [comment]
Hi, thanks  for your attention to our work.
1&2. We will open the source code when our another work DocScanner is accepted.
3. I do not quite understand the third question.

**Comment by CVUsers** [comment]
How is your docscanner implemented? Can you give us a general idea? Semantic or instance segmentation or key point detection?

**Comment by fh2019ustc** [comment]
You can refer to the paper for details.
https://arxiv.org/pdf/2110.14968.pdf
