### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by JerryBryant24** [fh2019ustc/DocTr#8]
Hello, can I train the model by myself with this code please?

**Comment by fh2019ustc** [comment]
Sure. You can complete the training code with the code of our network.

**Comment by JerryBryant24** [comment]
However, I did not see the code for model training in the compressed
package.

Hao Feng ***@***.***> 于2022年4月19日周二 10:32写道：

**Comment by JerryBryant24** [comment]
Hi, can I see the code for training the model?

**Comment by fh2019ustc** [comment]
Hi, thanks for your attention to our work. 
We will release the training code when the work "DocScanner" is accepted.
Besides, the code of "DocScanner" will be released at that time.

**Comment by JerryBryant24** [comment]
Ok, thank you very much!
